climatepulse:
  target: dev

  outputs:
    dev:
      type: duckdb
      path: data/climatepulse.duckdb
      schema: main
      threads: 4
      settings:
        TimeZone: UTC
    ci:
      type: duckdb
      path: data/climatepulse_ci.duckdb
      schema: main
      threads: 4
      settings:
        TimeZone: UTC
